packages:
  - packages/*
  - packages/@unjs/*
  - apps/*
  - apps/site/*
  - tests
  - tests/e2e

onlyBuiltDependencies:
  - esbuild

patchedDependencies:
  unenv@2.0.0-rc.24: patches/unenv@2.0.0-rc.24.patch
